version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^dependabot.*$/

jobs:
  build:
    working_directory: ~/camel-lsp-client-vscode
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-libxss1
          command: sudo apt-get install libxss1
      - run:
          name: install-typescript
          command: sudo npm install -g typescript
      - run:
          name: install-vsce
          command: sudo npm install -g vsce
      - run:
          name: npm-ci
          command: npm ci
      - run:
          name: npm-vscode:prepublish
          command: npm run vscode:prepublish
      - run:
          name: vsce-package
          command: vsce package
      - run:
          name: test
          command: npm test
      - run:
          name: test UI
          command: npm ui-test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

