version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/camel-lsp-client-vscode
    docker:
      - image: circleci/node:lts-buster-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: test java
          command: java --version
      - run:
          name: install-typescript
          command: sudo npm install -g typescript
      - run:
          name: install-vsce
          command: sudo npm install -g vsce
      - run:
          name: npm-ci
          command: npm ci
      - run:
          name: npm-vscode:prepublish
          command: npm run vscode:prepublish
      - run:
          name: vsce-package
          command: vsce package
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: /tmp/log-camel-lsp.out
      - store_artifacts:
          path: /home/circleci/.config/Code/logs
      - store_artifacts:
          path: /home/circleci/.config/Code/User/workspaceStorage/
      - store_artifacts:
          path: /tmp/grapes
      - run:
          name: test UI
          command: npm run ui-test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

